name: flutter_application_api_coin
description: "A new Flutter project - API Coin Market Cap"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1                   # Para fazer as chamadas HTTP
  provider: ^6.1.2               # Para Gerenciamento de Estado (ViewModel)
  intl: ^0.19.0                  # Para formatar as moedas (USD/BRL)
  cached_network_image: ^3.3.1

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
